export class UpdateDietaryProfile {
  constructor(
    public birthday: string,
    public gender: string,
    public heightCm: number,
    public heightFeet: number,
    public heightInches: number,
    public weightKg: number,
    public weightLbs: number,
    public activityLevel: string,
    public goal: string,
    public customCalories: number,
    public trackCalories: boolean,
    // public customFat: number,
    // public trackFat: boolean,
    public customSaturatedFat: number,
    public trackSaturatedFat: boolean,
    public customCarbohydrate: number,
    public trackCarbohydrate: boolean,
    public customAddedSugars: number,
    public trackAddedSugars: boolean,
    public customFiber: number,
    public trackFiber: boolean,
    public customProtein: number,
    public trackProtein: boolean,
    public customSodium: number,
    public trackSodium: boolean,
    public customCholesterol: number,
    public trackCholesterol: boolean,
    public customVitaminA: number,
    public trackVitaminA: boolean,
    public customVitaminC: number,
    public trackVitaminC: boolean,
    public customVitaminD: number,
    public trackVitaminD: boolean,
    public customCalcium: number,
    public trackCalcium: boolean,
    public customIron: number,
    public trackIron: boolean,
    public customPotassium: number,
    public trackPotassium: boolean,
    public customMagnesium: number,
    public trackMagnesium: boolean
  ) {}
}
