version: '3.4'

services:
  account: 
    image: ${DOCKER_REGISTRY}:account-latest
    container_name: pa-account
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${EVENT_BUS_HOST}
      - EventBusUserName=${EVENT_BUS_USERNAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    ports:
      - "5000:80"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  api:
    image: ${DOCKER_REGISTRY}:api-latest
    container_name: pa-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${EVENT_BUS_HOST}
      - EventBusUserName=${EVENT_BUS_USERNAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    ports:
      - "5001:80"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    image: ${DOCKER_REGISTRY}:gateway-latest
    container_name: pa-gateway
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    ports:
      - "5003:80"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - core-api
      - todo-api
      - weatherman-api

  core-api:
    image: ${DOCKER_REGISTRY}:core-api-latest
    container_name: pa-core-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  todo-api:
    image: ${DOCKER_REGISTRY}:todo-api-latest
    container_name: pa-todo-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${EVENT_BUS_HOST}
      - EventBusUserName=${EVENT_BUS_USERNAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  weatherman-api:
    image: ${DOCKER_REGISTRY}:weatherman-api-latest
    container_name: pa-weatherman-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  clientlogger:
    image: ${DOCKER_REGISTRY}:clientlogger-latest
    container_name: pa-clientlogger
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${CONNECTION_STRING}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  sender:
    image: ${DOCKER_REGISTRY}:sender-latest
    container_name: pa-sender
    restart: always
    environment:
      - EventBusConnection=${EVENT_BUS_HOST}
      - EventBusUserName=${EVENT_BUS_USERNAME}
      - EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:12
    container_name: pa-postgres
    restart: always
    ports:
      - '5445:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: pa-rabbitmq
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${EVENT_BUS_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${EVENT_BUS_PASSWORD}
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

volumes:
  postgres-data:
