version: '3.4'

services:
  personalassistant-web: 
    image: ${DOCKER_REGISTRY}:personalassistant-web-latest
    container_name: pa-web
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RabbitMQ__EventBusConnection=${EVENT_BUS_HOST}
      - RabbitMQ__EventBusUserName=${EVENT_BUS_USERNAME}
      - RabbitMQ__EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    ports:
      - "5000:80"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  gateway:
    image: ${DOCKER_REGISTRY}:gateway-latest
    container_name: pa-gateway
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    ports:
      - "5003:80"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - core-api
      - todo-api
      - cooking-api
      - accountant-api
      - weatherman-api
      - trainer-api

  core-api:
    image: ${DOCKER_REGISTRY}:core-api-latest
    container_name: pa-core-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  todo-api:
    image: ${DOCKER_REGISTRY}:todo-api-latest
    container_name: pa-todo-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RabbitMQ__EventBusConnection=${EVENT_BUS_HOST}
      - RabbitMQ__EventBusUserName=${EVENT_BUS_USERNAME}
      - RabbitMQ__EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  cooking-api:
    image: ${DOCKER_REGISTRY}:cooking-api-latest
    container_name: pa-cooking-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RabbitMQ__EventBusConnection=${EVENT_BUS_HOST}
      - RabbitMQ__EventBusUserName=${EVENT_BUS_USERNAME}
      - RabbitMQ__EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  accountant-api:
    image: ${DOCKER_REGISTRY}:accountant-api-latest
    container_name: pa-accountant-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  weatherman-api:
    image: ${DOCKER_REGISTRY}:weatherman-api-latest
    container_name: pa-weatherman-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  trainer-api:
    image: ${DOCKER_REGISTRY}:trainer-api-latest
    container_name: pa-trainer-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
      - PORT=80
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres

  sender:
    image: ${DOCKER_REGISTRY}:sender-latest
    container_name: pa-sender
    restart: always
    environment:
      - RabbitMQ__EventBusConnection=${EVENT_BUS_HOST}
      - RabbitMQ__EventBusUserName=${EVENT_BUS_USERNAME}
      - RabbitMQ__EventBusPassword=${EVENT_BUS_PASSWORD}
      - KeyVault__ClientSecret=${KEY_VAULT_SECRET}
    volumes:
      - ./storage:/app/storage
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: pa-postgres
    restart: always
    ports:
      - '5445:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: pa-rabbitmq
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${EVENT_BUS_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${EVENT_BUS_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  postgres-data:
