version: '3.4'

services:
  account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${EVENT_BUS_HOST:-rabbitmq}
      - EventBusUserName=${EVENT_BUS_USERNAME:-rabbitmq}
      - EventBusPassword=${EVENT_BUS_PASSWORD:-rabbitmq}
      - AdminEmail=${ADMIN_EMAIL}
      - Auth0__ClientSecret=${AUTH0_CLIENT_SECRET}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - PORT=80
    volumes:
      - ./src/Account/storage:/app/storage:z
    ports:
      - "5000:80"

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    volumes:
      - ./src/Gateway/storage:/app/storage:z
    ports:
      - "5003:80"

  core-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - PORT=80
    volumes:
      - ./src/Core.Api/storage:/app/storage:z
    ports:
      - "5004:80"

  todo-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${EVENT_BUS_HOST:-rabbitmq}
      - EventBusUserName=${EVENT_BUS_USERNAME:-rabbitmq}
      - EventBusPassword=${EVENT_BUS_PASSWORD:-rabbitmq}
      - PORT=80
    volumes:
      - ./src/ToDoAssistant.Api/storage:/app/storage:z
    ports:
      - "5005:80"

  cooking-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${EVENT_BUS_HOST:-rabbitmq}
      - EventBusUserName=${EVENT_BUS_USERNAME:-rabbitmq}
      - EventBusPassword=${EVENT_BUS_PASSWORD:-rabbitmq}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - PORT=80
    volumes:
      - ./src/CookingAssistant.Api/storage:/app/storage:z
    ports:
      - "5006:80"

  accountant-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    volumes:
      - ./src/Accountant.Api/storage:/app/storage:z
    ports:
      - "5007:80"

  weatherman-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    volumes:
      - ./src/Weatherman.Api/storage:/app/storage:z
    ports:
      - "5008:80"

  trainer-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    volumes:
      - ./src/Trainer.Api/storage:/app/storage:z
    ports:
      - "5009:80"

  clientlogger:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PORT=80
    volumes:
      - ./src/ClientLogger/storage:/app/storage:z
    ports:
      - "5002:80"

  sender:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - EventBusConnection=${EVENT_BUS_HOST:-rabbitmq}
      - EventBusUserName=${EVENT_BUS_USERNAME:-rabbitmq}
      - EventBusPassword=${EVENT_BUS_PASSWORD:-rabbitmq}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - ToDoAssistantVapid__PublicKey=${TODO_VAPID_PUBLIC_KEY}
      - ToDoAssistantVapid__PrivateKey=${TODO_VAPID_PRIVATE_KEY}
      - CookingAssistantVapid__PublicKey=${COOKING_VAPID_PUBLIC_KEY}
      - CookingAssistantVapid__PrivateKey=${COOKING_VAPID_PRIVATE_KEY}
    volumes:
      - ./src/Sender/storage:/app/storage:z

  postgres:
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - personalassistant-volume:/var/lib/postgresql/data

  rabbitmq:
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE:-cookie}
      RABBITMQ_DEFAULT_USER: ${EVENT_BUS_USERNAME:-rabbitmq}
      RABBITMQ_DEFAULT_PASS: ${EVENT_BUS_PASSWORD:-rabbitmq}
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

volumes:
  personalassistant-volume:
