export class DailyIntake {
  calories: number;
  customCalories: number;
  trackCalories: boolean;
  // fat: number;
  // customFat: number;
  // trackFat: boolean;
  saturatedFat: number;
  customSaturatedFat: number;
  trackSaturatedFat: boolean;
  carbohydrate: number;
  customCarbohydrate: number;
  trackCarbohydrate: boolean;
  addedSugars: number;
  customAddedSugars: number;
  trackAddedSugars: boolean;
  fiber: number;
  customFiber: number;
  trackFiber: boolean;
  protein: number;
  customProtein: number;
  trackProtein: boolean;
  sodium: number;
  customSodium: number;
  trackSodium: boolean;
  cholesterol: number;
  customCholesterol: number;
  trackCholesterol: boolean;
  vitaminA: number;
  customVitaminA: number;
  trackVitaminA: boolean;
  vitaminC: number;
  customVitaminC: number;
  trackVitaminC: boolean;
  vitaminD: number;
  customVitaminD: number;
  trackVitaminD: boolean;
  calcium: number;
  customCalcium: number;
  trackCalcium: boolean;
  iron: number;
  customIron: number;
  trackIron: boolean;
  potassium: number;
  customPotassium: number;
  trackPotassium: boolean;
  magnesium: number;
  customMagnesium: number;
  trackMagnesium: boolean;
}
