export class DailyIntake {
  public calories: number;
  public customCalories: number;
  public trackCalories: boolean;
  // public fat: number;
  // public customFat: number;
  // public trackFat: boolean;
  public saturatedFat: number;
  public customSaturatedFat: number;
  public trackSaturatedFat: boolean;
  public carbohydrate: number;
  public customCarbohydrate: number;
  public trackCarbohydrate: boolean;
  public addedSugars: number;
  public customAddedSugars: number;
  public trackAddedSugars: boolean;
  public fiber: number;
  public customFiber: number;
  public trackFiber: boolean;
  public protein: number;
  public customProtein: number;
  public trackProtein: boolean;
  public sodium: number;
  public customSodium: number;
  public trackSodium: boolean;
  public cholesterol: number;
  public customCholesterol: number;
  public trackCholesterol: boolean;
  public vitaminA: number;
  public customVitaminA: number;
  public trackVitaminA: boolean;
  public vitaminC: number;
  public customVitaminC: number;
  public trackVitaminC: boolean;
  public vitaminD: number;
  public customVitaminD: number;
  public trackVitaminD: boolean;
  public calcium: number;
  public customCalcium: number;
  public trackCalcium: boolean;
  public iron: number;
  public customIron: number;
  public trackIron: boolean;
  public potassium: number;
  public customPotassium: number;
  public trackPotassium: boolean;
  public magnesium: number;
  public customMagnesium: number;
  public trackMagnesium: boolean;
}
