name: Continuous deployment Accountant

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/Application/Domain/**"
      - "src/Application/Core.Application/**"
      - "src/Application/Accountant.Application/**"
      - "src/Application/Accountant.Application.Fs/**"
      - "src/Infrastructure/Core.Infrastructure/**"
      - "src/Infrastructure/Core.Persistence/**"
      - "src/Infrastructure/Accountant.Persistence/**"
      - "src/Infrastructure/Accountant.Persistence.Fs/**"
      - "src/Web/Accountant.Api/**"

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  deploy:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build accountant-api-latest image
        run: docker build -f ./src/Web/Accountant.Api/Dockerfile . --tag ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:accountant-api-latest

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Publish accountant-api-latest image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:accountant-api-latest
