name: Continuous deployment Account

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/Domain/**"
      - "src/Application/**"
      - "src/Infrastructure/**"
      - "src/Persistence/**"
      - "src/ToDoAssistant.Application/**"
      - "src/CookingAssistant.Application/**"
      - "src/Accountant.Application/**"
      - "src/ToDoAssistant.Persistence/**"
      - "src/CookingAssistant.Persistence/**"
      - "src/Accountant.Persistence/**"
      - "src/Account/**"

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  deploy:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Account image
        run: docker build -f ./src/Account/Dockerfile . --tag ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:account-latest

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Publish Account image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:account-latest
