name: Continuous deployment Api

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/Api/**"
      - "src/Domain/**"
      - "src/Application/**"
      - "src/ToDoAssistant.Application/**"
      - "src/CookingAssistant.Application/**"
      - "src/Accountant.Application/**"
      - "src/Weatherman.Application/**"
      - "src/Persistence/**"
      - "src/ToDoAssistant.Persistence/**"
      - "src/CookingAssistant.Persistence/**"
      - "src/Accountant.Persistence/**"
      - "src/Weatherman.Persistence/**"
      - "src/Utility/**"
      - "src/Infrastructure/**"

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  test:
    uses: davidtimovski/personal-assistant/.github/workflows/test.yml@master
  deploy:
    name: Build and push images to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Api image
        run: docker build -f ./src/Api/Dockerfile . --tag ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:api-latest

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Publish Api image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:api-latest
