name: Continuous deployment Core

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "*.targets"
      - "src/Core/Core.Application/**"
      - "src/Core/Core.Infrastructure/**"
      - "src/Core/Core.Persistence/**"
      - "src/Core/Core.Api/**"

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  REGISTRY_IMAGE: ${{ secrets.REGISTRY_IMAGE }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  deploy:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build core-api-latest image
        run: docker build -f ./src/Core/Core.Api/Dockerfile . --tag ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:core-api-latest

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Publish core-api-latest image
        run: docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_IMAGE }}:core-api-latest
