name: Continuous integration

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "src/Clients/**"

jobs:
  test:
    uses: davidtimovski/personal-assistant/.github/workflows/test.yml@dev
