name: Continuous integration

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "src/Accountant/accountant/**"
      - "src/Accountant/accountant2/**"
      - "src/CookingAssistant/cooking-assistant/**"
      - "src/ToDoAssistant/to-do-assistant/**"
      - "src/ToDoAssistant/to-do-assistant2/**"
      - "src/Trainer/trainer/**"
      - "src/Weatherman/weatherman/**"

jobs:
  test:
    uses: davidtimovski/personal-assistant/.github/workflows/test.yml@dev
