name: Testing dotnet

on:
  push:
    # branches: [ main ]
    branches: [ feature/docker ]

jobs:
  test:
    name: "Run unit tests"
    runs-on: windows-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
        with:
          dotnet-version: "5.0.100"
      - run: dotnet build test/Application.UnitTests/Application.UnitTests.csproj
      - run: dotnet test test/Application.UnitTests/Application.UnitTests.csproj