name: Testing dotnet

on:
  push:
    # branches: [ main ]
    branches: [ feature/docker ]

jobs:
  build-test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        dotnet: ['5.0.100', '5.0.201']
    steps:
      - uses: actions/checkout@v2
      - name: "Setup .NET Core ${{ matrix.dotnet }} on ${{ matrix.os }}"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build with dotnet
        run: |
          dotnet build test/Application.UnitTests/Application.UnitTests.csproj
          dotnet test test/Application.UnitTests/Application.UnitTests.csproj