name: Run unit tests

on:
  workflow_call:

jobs:
  test:
    name: Run unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest]
        os: [ windows-latest ]
        dotnet: ['7.0.100']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: "Setup .NET Core ${{ matrix.dotnet }} on ${{ matrix.os }}"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build Api.UnitTests
        run:
          dotnet build test/Api.UnitTests/Api.UnitTests.csproj
      - name: Test Api.UnitTests
        run:
          dotnet test test/Api.UnitTests/Api.UnitTests.csproj
      - name: Build Application.UnitTests
        run:
          dotnet build test/Application.UnitTests/Application.UnitTests.csproj
      - name: Test Application.UnitTests
        run:
          dotnet test test/Application.UnitTests/Application.UnitTests.csproj
